### ISSUE TITLE
Admin link doesn't work after submitting new campaign

### ISSUE THREAD

**Issue by ctrance** [mobilizingcs/navbar#20]
@stevenolen - I was testing the authoring tool on test.mobilizingcs, then submitted the newly created campaign. When I go to navbar and click "Admin" nothing happens.

**Comment by stevenolen** [comment]
Just tested this on Chrome 47 and it worked fine.  Any more steps you can think of to recreate? Could you try clearing your cache and repeating (mainly since I can't come up with a case where the campaign submit code could have any affect on the navbar..).

**Comment by ctrance** [comment]
I was using FF 42.0 on Windows 7

**Comment by ctrance** [comment]
@stevenolen - It worked after clearing my cache. I remember having a validation error before successfully submitting the new campaign from the auth tool. Then after successful submission I open Admin on the navbar but nothing happens.

**Comment by stevenolen** [comment]
huh. Thanks for that info! Since it went away when you cleared your cache, I'm going to close this since I think it was more a problem with "broken navbar due to some old cached code somewhere" than anything to do with the author tool.  Given the code @jeroenooms wrote in the last few days, it should have no affect on the navbar (given that the author tool executes in an iframe and did nothing to attempt to break out!).  Thanks for reporting!
